name: weather_forecast
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  swipeable_page_route: ^0.4.7
  bloc: ^9.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.16
  theme_manager: ^2.0.4
  http: ^1.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.6
  rename: ^3.1.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  # example:
  fonts:
    - family: Switzer
      fonts:
        - asset: assets/fonts/switzer/Switzer-Variable.ttf
        - asset: assets/fonts/switzer/Switzer-VariableItalic.ttf
          style: italic
